<a href="https://colab.research.google.com/github/SharonCao0920/AI/blob/main/CS483_Lecture_Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
"""
Question2
"""
import random
def crossover(parent1,parent2,crs_rate):
    p1,p2 = list(parent1),list(parent2) #convert str to list
    rand_cross = np.random.random()
    #print(rand_cross)

    if rand_cross < crs_rate:
      pt = np.random.randint(0,10)
      for i in range(pt,len(p1)):
          p1[i],p2[i] = p2[i],p1[i]       #swap the genetic information
    p1,p2 = ''.join(p1),''.join(p2)     #Convert list to str
    return p1,p2
    


parent = ['1101111001','1100001011','1100001011','1110010000','1101111001','1110010000',
          '1110100001','0011010000','1101111001','0100110010','1001011010','1101111001',
          '0111011111','1001110101','1101111001','1110100001']
print("Original Parent\n", parent)
child=[]
for i in range(int(len(parent)/2)):
  if i == 0:
    p1 = parent[i]
    p2 = parent[i+1]
  else:
    p1 = parent[i*2]
    p2 = parent[i*2+1] 

  offspring1,offspring2 = crossover(p1,p2,0.8)
  child.append(offspring1)
  child.append(offspring2)
print("After crossover\n", child)


Original Parent
 ['1101111001', '1100001011', '1100001011', '1110010000', '1101111001', '1110010000', '1110100001', '0011010000', '1101111001', '0100110010', '1001011010', '1101111001', '0111011111', '1001110101', '1101111001', '1110100001']
After crossover
 ['1101111001', '1100001011', '1100001011', '1110010000', '1110010000', '1101111001', '1110010000', '0011100001', '0100110010', '1101111001', '1001011010', '1101111001', '0101110101', '1011011111', '1110100001', '1101111001']


In [77]:
"""
Question3
"""
import numpy as np
def mutation(parent, mutation_rate):
  chro_s = len(parent[0])
  p_size = len(parent)
  size = chro_s*p_size*mutation_rate
  # print(chro_s)
  # print(p_size)
  print("Size is: ",size)
  for i in range(4):
    id = np.random.randint(0, p_size)
    pos = np.random.randint(0, chro_s)
    print(id, pos)
    print(parent[id])
    p = list(parent[id])
    print(p)
    if p[pos]=='0':
      p[pos] = '1'
    else:
      p[pos] = '0'
    print(p)
    parent[id]=''.join(p)
  return parent

mutation_rate = 0.025
parent=['1001011010','1110010000','0111010100','1110010101','0111010000',
        '1110010101','1110100011','1110100001','0100111000','0110010011',
        '1110001011','1000010010','0001011010','1011010000','1101101001','1110010000']
parent_m = mutation(parent, mutation_rate)
print("\nOriginal:\n", parent)
print("After mutation: \n",parent_m)

Size is:  4.0
12 9
0001011010
['0', '0', '0', '1', '0', '1', '1', '0', '1', '0']
['0', '0', '0', '1', '0', '1', '1', '0', '1', '1']
3 8
1110010101
['1', '1', '1', '0', '0', '1', '0', '1', '0', '1']
['1', '1', '1', '0', '0', '1', '0', '1', '1', '1']
12 6
0001011011
['0', '0', '0', '1', '0', '1', '1', '0', '1', '1']
['0', '0', '0', '1', '0', '1', '0', '0', '1', '1']
11 1
1000010010
['1', '0', '0', '0', '0', '1', '0', '0', '1', '0']
['1', '1', '0', '0', '0', '1', '0', '0', '1', '0']

Original:
 ['1001011010', '1110010000', '0111010100', '1110010111', '0111010000', '1110010101', '1110100011', '1110100001', '0100111000', '0110010011', '1110001011', '1100010010', '0001010011', '1011010000', '1101101001', '1110010000']
After mutation: 
 ['1001011010', '1110010000', '0111010100', '1110010111', '0111010000', '1110010101', '1110100011', '1110100001', '0100111000', '0110010011', '1110001011', '1100010010', '0001010011', '1011010000', '1101101001', '1110010000']


In [106]:
"""
Question 4
"""

import numpy as np
states = ["London", "Barcelona", "New York"]
n_states = len(states)   # =3

# observations = ["red", "white"]
# n_observations = len(observations)
start_probability = np.matrix([0.1, 0.6, 0.3]) 

transition_probability = np.matrix([
    [0.10, 0.70, 0.20],
    [0.75, 0.15, 0.10],
    [0.60, 0.35, 0.05] 
])
#after 1 day
P1 =start_probability * transition_probability
print("---Wednesday probability---")
print(states,"\n", P1)

#after 2 day
P2 =P1 * transition_probability
print("---Thursday probability---")
print(states,"\n", P2)
#after 3 day
P3 =P2 * transition_probability
print("---Friday probability---")
print(states,"\n", P3)

print("\n=====================Final Result======================")
for i in range(P3.size):
  print("Probability of in ", states[i], " on Friday is ", P3.item(0,i))


---Wednesday probability---
['London', 'Barcelona', 'New York'] 
 [[0.64  0.265 0.095]]
---Thursday probability---
['London', 'Barcelona', 'New York'] 
 [[0.31975 0.521   0.15925]]
---Friday probability---
['London', 'Barcelona', 'New York'] 
 [[0.518275  0.3577125 0.1240125]]

=====================Final Result======================
Probability of in  London  on Friday is  0.5182749999999999
Probability of in  Barcelona  on Friday is  0.35771249999999993
Probability of in  New York  on Friday is  0.12401249999999998
